# -*- coding: utf-8 -*-
"""scikit-learn_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18K4aEoZNuyWDbYyT4CjxVGv77BzYkxvq
"""

from sklearn.datasets import make_regression
import pandas as pd
import matplotlib.pyplot as plt

x, y = make_regression(
    random_state = 3,
    n_features = 1,
    noise = 10,
    bias = 100,
    n_samples = 300
)

df = pd.DataFrame(x)

plt.figure(figsize = (5, 5))
plt.scatter(df[0], y, color = 'b', alpha = 0.5)
plt.grid()
plt.show()

x, y = make_regression(
    random_state = 3,
    n_features = 1,
    noise = 0,
    bias = 100,
    n_samples = 300
)

df = pd.DataFrame(x)

plt.figure(figsize = (5, 5))
plt.scatter(df[0], y, color = 'b', alpha = 0.5)
plt.grid()
plt.show()