# -*- coding: utf-8 -*-
"""scikit-learn_circles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XGlpNOauCI_kU_gYZFW_ToDNCEOQwbt
"""

from sklearn.datasets import make_circles
import matplotlib.pyplot as plt
import pandas as pd

x, y = make_circles(
    random_state = 3,
    noise = 0.1,
    n_samples = 300
)

df = pd.DataFrame(x)
df["target"] = y

df0 = df[df["target"] == 0]
df1 = df[df["target"] == 1]

plt.figure(figsize = (5, 5))
plt.scatter(df0[0], df0[1], color = "blue")
plt.scatter(df1[0], df1[1], color = "red")
plt.grid()
plt.show()