# -*- coding: utf-8 -*-
"""intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sx4CmW788kVujRcsYG15cKRWTo6XYwNg
"""

print("Hello")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.plot([0,2,1,3])
plt.show()

