# -*- coding: utf-8 -*-
"""linear_regression_sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xDr7MDgVvEOBkfJtxh_e75rA00vBxmk
"""

# Commented out IPython magic to ensure Python compatibility.
from ast import increment_lineno
from sklearn.datasets import make_regression
from sklearn.metrics import accuracy_score
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

X, y = make_regression(random_state = 3, n_features = 1, noise = 20, n_samples = 30)
df = pd.DataFrame(X)
plt.figure(figsize = (5, 5))
plt.scatter(df[0], y, color = "b", alpha = 0.5)
plt.grid()
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)
score = r2_score(y_test, pred)
print("正解率: ", score * 100, "%")

plt.figure(figsize = (5, 5))
plt.scatter(X, y, color = "b", alpha = 0.5)
plt.plot(X, model.predict(X), color = "red")
plt.grid()
plt.show()

X, y = make_regression(random_state = 3, n_samples = 30, n_features = 1, noise = 80)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)
score = r2_score(y_test, pred)
print("正解率: ", score * 100, "%")

plt.figure(figsize = (5, 5))
plt.scatter(X, y, color = "b", alpha = 0.5)
plt.plot(X, model.predict(X), color = "red")
plt.grid()
plt.show()