# -*- coding: utf-8 -*-
"""scikit-learn_blobs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nj4zppRW9091h_SfO1M38jqIRwn64clM
"""

from sklearn.datasets import make_blobs
import pandas as pd

x, y = make_blobs(
    random_state = 3,
    n_features = 2,
    centers = 2,
    cluster_std = 1,
    n_samples = 300
)

df = pd.DataFrame(x)
df["target"] = y
df.head()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

df0 = df[df["target"] == 0]
df1 = df[df["target"] == 1]

plt.figure(figsize=(5, 5))
plt.scatter(df0[0], df0[1], color="b", alpha=0.5)
plt.scatter(df1[0], df1[1], color="r", alpha=0.5)
plt.grid()
plt.show()

# 3つの塊数
X, y = make_blobs(
    random_state = 3,
    n_features = 2,
    centers = 3,
    cluster_std = 1,
    n_samples = 300
)

df = pd.DataFrame(X)
df["target"] = y
df0 = df[df["target"] == 0]
df1 = df[df["target"] == 1]
df2 = df[df["target"] == 2]

plt.figure(figsize=(5, 5))
plt.scatter(df0[0], df0[1], color="b", alpha=0.5)
plt.scatter(df1[0], df1[1], color="r", alpha=0.5)
plt.scatter(df2[0], df2[1], color="g", alpha=0.5)
plt.grid()
plt.show()

# 5つの塊数
X, y = make_blobs(
    random_state = 3,
    n_features = 2,
    centers = 5,
    cluster_std = 1,
    n_samples = 300
)

df = pd.DataFrame(X)
df["target"] = y
df0 = df[df["target"] == 0]
df1 = df[df["target"] == 1]
df2 = df[df["target"] == 2]
df3 = df[df["target"] == 3]
df4 = df[df["target"] == 4]

plt.figure(figsize=(5, 5))
plt.scatter(df0[0], df0[1], color="b", alpha=0.5)
plt.scatter(df1[0], df1[1], color="r", alpha=0.5)
plt.scatter(df2[0], df2[1], color="g", alpha=0.5)
plt.scatter(df3[0], df3[1], color="m", alpha=0.5)
plt.scatter(df4[0], df4[1], color="c", alpha=0.5)
plt.grid()
plt.show()